### ISSUE TITLE
keys cannot contain : character

### ISSUE THREAD

**Issue by JadeVane** [mdouchement/standardfile#59]
I downloaded the binary file from the [release page](https://github.com/mdouchement/standardfile/releases), and run with the command below

```
./standardfile-linux-amd64 init -c standardfile.yml
```

the content of `standardfile.yml` was copied from [here](https://github.com/mdouchement/standardfile/blob/v0.6.4/standardfile.yml)

```
# Address to bind
address: "localhost:5000"
# Disable registration
no_registration: false
# Database folder path; empty value means current directory
database_path: ""
# Secret key used for JWT authenthentication (before 004 and 20200115)
secret_key: jwt-development
# Session used for authentication (since 004 and 20200115)
session:
  secret: paseto-development
  access_token_ttl: 1440h # 60 days expressed in Golang's time.Duration format
  refresh_token_ttl: 8760h # 1 year
```

but get the error message

```
Error: (2, 1): parsing error: keys cannot contain : character
Usage:
  standardfile init [flags]

Flags:
  -c, --config string   Configuration file
  -h, --help            help for init

2021/09/04 09:50:37 (2, 1): parsing error: keys cannot contain : character
```

some infomation that may be helpful

go version: `1.17 linux/amd64`
platform: `ubuntu 20.04`
kernel: `5.11.0-27-generic`
