### ISSUE TITLE
server not reachable

### ISSUE THREAD

**Issue by jakejoh** [mdouchement/standardfile#76]
I'm running standardfile in docker on a synology and can't connect to the server.

my standardfile.yml
```yml
address: "localhost:5000"
no_registration: false
database_path: "/data/database/"
secret_key: ...
session:
  secret: ...
  access_token_ttl: 1440h # 60 days expressed in Golang's time.Duration format
  refresh_token_ttl: 8760h # 1 year
```

I'm running the container as user 1029:100 and both the yml and the database are available inside the container:
```bash
uid=1029 gid=100(users)
/ $ ls -l etc/standardfile/
-rwxr-xr-x    1 1029     users          536 Jun  3 14:42 standardfile.yml
/ $ ls -l data/
drwxr-xr-x    1 1029     users           30 Jun  2 19:52 database
```

The log seems fine as well:
```
Routes:
[...]
   GET /version
2022/06/08 09:51:04 Server listening on localhost:5000
   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.7.2
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on 127.0.0.1:5000
```

however, when sending any request to the port I published (8084:5000) , e.g. a GET request to {serverip}:8084/version, I only receive a `Error: Failure when receiving data from the peer` without any logs.

Any idea what the issue might be?
Thanks a lot :)
